apiVersion: apps/v1
kind: deployment
metadata:
  name: mongodb-deployment
  labels: 
    app: mongodb
spec:
  replicas: 1
  selectors:
    matchlabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerport: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: